server:
  port: 8004


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000
spring:
  application:
    name: luokine-getway-service
zuul:
  routes:
    luokine-consumer-service:
      path: /consumer/**
      serviceId: luokine-consumer-service
      url: http://127.0.0.1:8002/
      strip-prefix: false
    luokine-user-service:
      path: /user/**
      serviceId: luokine-user-service
      url: http://127.0.0.1:8005/
      strip-prefix: false
    luokine-provider-service:
      path: /provider/**
      serviceId: luokine-provider-service
      url: http://127.0.0.1:8001/
      strip-prefix: false
