server:
  port: 8002


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000

#  swagger:
#    enabled: true
#    base-package: com.luokine.service.webcontroller
#    contact:
#      name: '组织机构服务'
