server:
  port: 8002


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000

#  swagger:
#    enabled: true
#    base-package: com.luokine.service.webcontroller
#    contact:
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luokine_user?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  mybatis-plus:
    type-aliases-package: com.luokine.service.dao
    mapper-locations: classpath*:mapping/**/*Mapper.xml
    configuration:
      map-underscore-to-camel-case: true
#  security:
#    user:
#      name: admin
#      password: admin